name: Synchro
version: '${version}'
main: org.redstone.SynhroPlugin
api-version: '1.18'
description: A plugin that synchronizes inventory, health and hunger between players
author: Redstone
folia-supported: true
commands:
  synchro:
    description: Synchro plugin admin command
    usage: /<command> <enable|disable|sync|status>
    permission: synchro.admin
